# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01264c911d3a20c96efd6a7391c06831464d381213e12275dec94beea8489a923fe298859478c21df06e3e8d4c34138629b19cd4b84a866da52cbb739cb175f0

test:
  secret_key_base: a46b9e0c878b8d4ca65ee00037ec939a60487f0ff2f83faeedad23faf6a194b67c754a46031cc92145d45dff740da1ac17caaa4fd5d7c42cad10c14fc7f0a77f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
